sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t paisit04/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true paisit04/react-test npm test

after_success:
  - docker build -t paisit04/multi-client ./client
  - docker build -t paisit04/multi-nginx ./nginx
  - docker build -t paisit04/multi-server ./server
  - docker build -t paisit04/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push paisit04/multi-client
  - docker push paisit04/multi-nginx
  - docker push paisit04/multi-server
  - docker push paisit04/multi-worker

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-659821968821"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
